/**
 * @fileoverview gRPC-Web generated client stub for score
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.15.6
// source: protoFiles/proto/score.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protoFiles_proto_score_pb from '../../protoFiles/proto/score_pb';


export class ScoresClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAggregatedCategoryScoresForPeriod = new grpcWeb.MethodDescriptor(
    '/score.Scores/GetAggregatedCategoryScoresForPeriod',
    grpcWeb.MethodType.UNARY,
    protoFiles_proto_score_pb.Interval,
    protoFiles_proto_score_pb.AggregatedCategoryScoresResponse,
    (request: protoFiles_proto_score_pb.Interval) => {
      return request.serializeBinary();
    },
    protoFiles_proto_score_pb.AggregatedCategoryScoresResponse.deserializeBinary
  );

  getAggregatedCategoryScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null): Promise<protoFiles_proto_score_pb.AggregatedCategoryScoresResponse>;

  getAggregatedCategoryScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.AggregatedCategoryScoresResponse) => void): grpcWeb.ClientReadableStream<protoFiles_proto_score_pb.AggregatedCategoryScoresResponse>;

  getAggregatedCategoryScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.AggregatedCategoryScoresResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/score.Scores/GetAggregatedCategoryScoresForPeriod',
        request,
        metadata || {},
        this.methodDescriptorGetAggregatedCategoryScoresForPeriod,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/score.Scores/GetAggregatedCategoryScoresForPeriod',
    request,
    metadata || {},
    this.methodDescriptorGetAggregatedCategoryScoresForPeriod);
  }

  methodDescriptorGetTicketScoresForPeriod = new grpcWeb.MethodDescriptor(
    '/score.Scores/GetTicketScoresForPeriod',
    grpcWeb.MethodType.UNARY,
    protoFiles_proto_score_pb.Interval,
    protoFiles_proto_score_pb.TicketScoresResponse,
    (request: protoFiles_proto_score_pb.Interval) => {
      return request.serializeBinary();
    },
    protoFiles_proto_score_pb.TicketScoresResponse.deserializeBinary
  );

  getTicketScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null): Promise<protoFiles_proto_score_pb.TicketScoresResponse>;

  getTicketScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.TicketScoresResponse) => void): grpcWeb.ClientReadableStream<protoFiles_proto_score_pb.TicketScoresResponse>;

  getTicketScoresForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.TicketScoresResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/score.Scores/GetTicketScoresForPeriod',
        request,
        metadata || {},
        this.methodDescriptorGetTicketScoresForPeriod,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/score.Scores/GetTicketScoresForPeriod',
    request,
    metadata || {},
    this.methodDescriptorGetTicketScoresForPeriod);
  }

  methodDescriptorGetOverallScoreForPeriod = new grpcWeb.MethodDescriptor(
    '/score.Scores/GetOverallScoreForPeriod',
    grpcWeb.MethodType.UNARY,
    protoFiles_proto_score_pb.Interval,
    protoFiles_proto_score_pb.OverallScoreResponse,
    (request: protoFiles_proto_score_pb.Interval) => {
      return request.serializeBinary();
    },
    protoFiles_proto_score_pb.OverallScoreResponse.deserializeBinary
  );

  getOverallScoreForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null): Promise<protoFiles_proto_score_pb.OverallScoreResponse>;

  getOverallScoreForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.OverallScoreResponse) => void): grpcWeb.ClientReadableStream<protoFiles_proto_score_pb.OverallScoreResponse>;

  getOverallScoreForPeriod(
    request: protoFiles_proto_score_pb.Interval,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protoFiles_proto_score_pb.OverallScoreResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/score.Scores/GetOverallScoreForPeriod',
        request,
        metadata || {},
        this.methodDescriptorGetOverallScoreForPeriod,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/score.Scores/GetOverallScoreForPeriod',
    request,
    metadata || {},
    this.methodDescriptorGetOverallScoreForPeriod);
  }

}

